[workspace]

members = [
    "node",
    "node/stream",
    "node/log_entry_sync",
    "node/rpc",
    "node/kv_types",
    "node/storage_with_stream",
]
resolver = "2"

[patch.crates-io]
eth2_ssz = { path = "version-meld/eth2_ssz" }
enr = { path = "version-meld/enr" }
discv5 = { path = "version-meld/discv5" }

[workspace.dependencies]
append_merkle = { git = "https://github.com/0glabs/0g-storage-node.git",rev = "a79f7bbf126df3748d072076dccdc7e0c34bd971" }
merkle_light = { git = "https://github.com/0glabs/0g-storage-node.git",rev = "a79f7bbf126df3748d072076dccdc7e0c34bd971" }
merkle_tree = { git = "https://github.com/0glabs/0g-storage-node.git",rev = "a79f7bbf126df3748d072076dccdc7e0c34bd971" }
shared_types = { git = "https://github.com/0glabs/0g-storage-node.git",rev = "a79f7bbf126df3748d072076dccdc7e0c34bd971" }
task_executor = { git = "https://github.com/0glabs/0g-storage-node.git",rev = "a79f7bbf126df3748d072076dccdc7e0c34bd971" }
storage = { git = "https://github.com/0glabs/0g-storage-node.git",rev = "a79f7bbf126df3748d072076dccdc7e0c34bd971" }
contract-interface = { git = "https://github.com/0glabs/0g-storage-node.git",rev = "a79f7bbf126df3748d072076dccdc7e0c34bd971" }