[workspace]

members = [
    "node",
    "node/stream",
    "node/log_entry_sync",
    "node/rpc",
    "node/kv_types",
    "node/storage_with_stream",
]
resolver = "2"

[patch.crates-io]
eth2_ssz = { path = "version-meld/eth2_ssz" }
enr = { path = "version-meld/enr" }
discv5 = { path = "version-meld/discv5" }
